### PR TITLE
Update supported OS and OpenShift Note

### PR DESCRIPTION
**Pull request by gnarl**
@juliantap let me know if you have any questions about this change.

### CODE REVIEW

**Review by juliantap — APPROVED** [review]
Approved with no questions.

**Comment by juliantap** [comment]
@gnarl Should this be merged now or with 22.01 release? Not sure if this is break-fix or release related.

**Comment by gnarl** [comment]
@juliantap it is a break-fix and should be included with the Trident 21.10 documentation.

The team found that the minimum K8S version needs to be updated from 1.14 to 1.17 as well. I did a search on the repo and didn't find "1.14" used anywhere else.

I then promptly messed up squashing the commits before pushing the changes back to this fork. Let me know if you'd like for me to start over. If you have a git flow for making changes on an existing fork please let me know what the steps are. Thanks!

**Comment by gnarl** [comment]
@juliantap, would we be able to use [custom attributes](https://docs.asciidoctor.org/asciidoc/latest/attributes/reference-attributes/#reference-custom) so that we'd have one place to update version information in the documentation? Where it makes sense we could set use {min-k8s-version} in the documentation. Let me know if you think this would be useful or not.

**Comment by juliantap** [comment]
@gnarl I couldn't figure out how to import that last commit (for the min K8s version), so I made the change in the repo and pushed to prod. 

Your PRs will always fail because you're still not a member of NetAppDocs. Let me know if you want to me to reinititiate this request. And I can't override the failure because I'm not a GH admin. Therefore, I created a new PR. It should preserve your commits (for the first two that I could import), but I'm not sure what it will do with the squashed one. 

All changes have been made under PR https://github.com/NetAppDocs/trident/pull/54/files  

> 

I would *love* to use custom attributes. I don't think any of us are using this currently, but it reminds me of "variables" in days of SGML yore. Let me play with it and run it by our tools team to make sure I won't break anything if I start using it. Then we can plan our attribute mapping.

**Comment by gnarl** [comment]
@juliantap please send the request again and I promise to dig into it this time. 

Thanks for fixing the PR and getting it merged!

**Pull request closed without merging**
