### PR TITLE
Update docs to reflect ONTAP-nas-flexgroup supports snapshots

### PR DESCRIPTION
**Pull request by adkerr**
These 2 commits could be merged into 1

### CODE REVIEW

**Comment by gnarl** [comment]
@juliantap, can you look through the documentation and make sure we don't need to reference ontap-nas-flexgroup driver with snapshots anywhere else?

The [TR](https://www.netapp.com/pdf.html?item=/media/17064-tr4678pdf.pdf) is helpful in describing how a FlexGroup snapshot differs from an ONTAP snapshot. I told Andrew to call it a "NetApp FlexGroup snapshot" but after reading the Trident documentation again this might not be needed.

**Comment by juliantap** [comment]
> @juliantap, can you look through the documentation and make sure we don't need to reference ontap-nas-flexgroup driver with snapshots anywhere else?
> 
> The [TR](https://www.netapp.com/pdf.html?item=/media/17064-tr4678pdf.pdf) is helpful in describing how a FlexGroup snapshot differs from an ONTAP snapshot. I told Andrew to call it a "NetApp FlexGroup snapshot" but after reading the Trident documentation again this might not be needed.

Will do!

**Comment by juliantap** [comment]
@adkerr & @gnarl Should ontap-nas-flexgroup be added everywhere we reference ontap-nas? Or only where snapshots are specifically referenced? 

These topics directly reference snapshots. Do they need to be updated to include the flexgroup driver?

- https://docs.netapp.com/us-en/trident/faq.html#what-are-the-drivers-that-support-astra-trident-volume-snapshots
- https://docs.netapp.com/us-en/trident/trident-reco/backup.html#recover-date-by-using-ontap-snapshots

**Comment by gnarl** [comment]
@juliantap, this PR is to specifically document that snapshots for the ontap-nas-flexgroup driver are supported. The two links that you mentioned should also be updated. If needed you can also ask me questions in Slack.

**Comment by juliantap** [comment]
Original @adkerr patch changes combined with additional related doc updates for this flexgroup driver snapshot combined into https://github.com/NetAppDocs/trident/pull/57. Closing this PR as duplicate.

**Pull request closed without merging**
